### ISSUE TITLE
Can't select bus 0

### ISSUE THREAD

**Issue by simonnilsson** [aphotix/raspi-node-sht31#3]
On the following line device is OR:ed with 1, meaning it is not possible to select bus 0, it will use bus 1 instead.
https://github.com/aphotix/raspi-node-sht31/blob/2d5f2a10fce9cc99375ed53260e74d847b03ed89/src/index.js#L9

**Comment by aphotix** [comment]
@simonnilsson Good call, seems so obvious when you point it out.
